#! /usr/bin/env bash

echo "== Put Bucket =="

# Check for bucket name
if [ -z "$1" ]; then
    echo "There needs to be a bucket name eg. ./bucket my-bucket-name."
    exit
fi

# Check for filename prefix
if [ -z "$2" ]; then
    echo "There needs to be a file name eg. ./bucket/my-bucket-name my-file-name."
    exit
fi

BUCKET_NAME=$1

FILENAME=$2

OBJECT_KEY=$(basename "$FILENAME")

aws s3api put-object --bucket $BUCKET_NAME --body $FILENAME --key $OBJECT_KEY